#!/bin/bash

x="$(echo -e "dwarf fortress\ncataclysm" | dmenu -z 295 -p "Linux Games")"
    if [ "$x" == 'dwarf fortress' ]; then
        ps -C Dwarf_Fortress >/dev/null && echo "Running" || dwarffortress &
        sleep 3
        ps -C dwarftherapist >/dev/null && echo "Running" || dwarftherapist 
    fi
    if [ "$x" == 'cataclysm' ]; then
        alacritty --class games -e cataclysm
    fi
