#!/bin/bash
function media_menu {
    x="$(echo -e "kvf\nradio" | dmenu -z 295 -p "media")"
    if [ "$x" == 'kvf' ]; then
        xdotool key alt+b
        mpv 'https://play.kringvarp.fo/redirect/kvf/_definst_/720?type=m3u8'
        trap "xdotool key alt+b" INT
    fi
    if [ "$x" == 'radio' ]; then
        alacritty --class radio -e radio
    fi
}

case $BUTTON in
1)
    media_menu
    ;;
3) alacritty -e code "$0" ;;
esac
